export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';
export const SEARCH_MOVIES_CLEANUP = 'SEARCH_MOVIES_CLEANUP';
