export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';
export const SEARCH_MOVIES_CLEANUP = 'SEARCH_MOVIES_CLEANUP';

export const NOMINATION_START = 'NOMINATION_START';
export const NOMINATION_SUCCESS = 'NOMINATION_SUCCESS';
export const NOMINATION_FAIL = 'NOMINATION_FAIL';
export const NOMINATION_ADD = 'NOMINATION_ADD';
export const NOMINATION_REMOVE = 'NOMINATION_REMOVE';
export const NOMINATION_CLEANUP = 'NOMINATION_CLEANUP';
